# Generated by Django 3.2.7 on 2021-11-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
                ('open_hours', models.DateTimeField(verbose_name='Opening Hour')),
                ('closing_hours', models.DateTimeField(verbose_name='Closing Hour')),
                ('address', models.CharField(max_length=250)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.itinerary')),
            ],
        ),
    ]
