# Generated by Django 3.2.7 on 2021-11-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_itinerary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='closing_hours',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='open_hours',
            field=models.TimeField(),
        ),
    ]
