# Generated by Django 3.2.7 on 2021-11-05 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211105_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='arrival_date',
            field=models.DateField(default=datetime.date(2021, 11, 5), verbose_name='Arrival Date'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='city',
            field=models.CharField(default='Seattle', max_length=100),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='departure_date',
            field=models.DateField(default=datetime.date(2021, 11, 5), verbose_name='Departure Date'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
