# Generated by Django 3.2.7 on 2021-11-08 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211105_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='arrival_date',
            field=models.DateField(default=datetime.date(2021, 11, 8), verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='departure_date',
            field=models.DateField(default=datetime.date(2021, 11, 8), verbose_name='Departure Date'),
        ),
    ]
