# Generated by Django 3.2.8 on 2021-11-11 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20211110_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.date(2021, 11, 11), verbose_name='Posted on'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='arrival_date',
            field=models.DateField(default=datetime.date(2021, 11, 11), verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='departure_date',
            field=models.DateField(default=datetime.date(2021, 11, 11), verbose_name='Departure Date'),
        ),
    ]
